## **Business Understanding**

**About Data**: Derived from simple hierarchical decision model, this database may be useful for testing constructive induction and structure discovery methods.

Additional Information

Car Evaluation Database was derived from a simple hierarchical decision model originally developed for the demonstration of DEX, M. Bohanec, V. Rajkovic: Expert system for decision making. Sistemica 1(1), pp. 145-157, 1990.). The model evaluates cars according to the following concept structure:

CAR car acceptability . PRICE overall price . . buying buying price . . maint price of the maintenance . TECH technical characteristics . . COMFORT comfort . . . doors number of doors . . . persons capacity in terms of persons to carry . . . lug_boot the size of luggage boot . . safety estimated safety of the car

Input attributes are printed in lowercase. Besides the target concept (CAR), the model includes three intermediate concepts: PRICE, TECH, COMFORT. Every concept is in the original model related to its lower level descendants by a set of examples (for these examples sets see http://www-ai.ijs.si/BlazZupan/car.html).

The Car Evaluation Database contains examples with the structural information removed, i.e., directly relates CAR to the six input attributes: buying, maint, doors, persons, lug_boot, safety.

Because of known underlying concept structure, this database may be particularly useful for testing constructive induction and structure discovery methods.

Bohanec, M. (1988). Car Evaluation [Dataset]. UCI Machine Learning Repository. https://doi.org/10.24432/C5JP48. Data Source

### **Load Library**

In [3]:
import pandas as pd

#### **Load Data**

In [15]:
columns = ["buying", "maint", "doors","persons","lug_boot","safety", "class"]

In [12]:
df = pd.read_csv("data/car+evaluation/car.data")

In [14]:
df.head()

   vhigh vhigh.1  2 2.1  small   low  unacc
0  vhigh   vhigh  2   2  small   med  unacc
1  vhigh   vhigh  2   2  small  high  unacc
2  vhigh   vhigh  2   2    med   low  unacc
3  vhigh   vhigh  2   2    med   med  unacc
4  vhigh   vhigh  2   2    med  high  unacc

In [7]:
df.tail()

     vhigh vhigh.1      2   2.1 small   low  unacc
1722   low     low  5more  more   med   med   good
1723   low     low  5more  more   med  high  vgood
1724   low     low  5more  more   big   low  unacc
1725   low     low  5more  more   big   med   good
1726   low     low  5more  more   big  high  vgood

Getting the dimensions of the data

In [8]:
rows, columns= df.shape
output =f"{columns} features and {rows} records"
print(output)

7 features and 1727 records

#### **Get a summary of the structure of the table**

data types
Non nulll value counts
Memory usage

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1727 entries, 0 to 1726
Data columns (total 7 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   vhigh    1727 non-null   str
 1   vhigh.1  1727 non-null   str
 2   2        1727 non-null   str
 3   2.1      1727 non-null   str
 4   small    1727 non-null   str
 5   low      1727 non-null   str
 6   unacc    1727 non-null   str
dtypes: str(7)
memory usage: 133.4 KB

In [16]:
df.rename(columns={'buying': 'buyingPrice'}, inplace=True)
df.rename(columns={'maint': 'priceofMaintenance'}, inplace=True)
df.rename(columns={'lug_boot': 'sizeLuggageBoot'}, inplace=True)
df.rename(columns={'safety': 'estimatedCarSafety'}, inplace=True)
df.rename(columns={'persons': 'carPassengerCapacity'}, inplace=True) 
df.rename(columns={'doors': 'numberOfdoors'}, inplace=True)

In [17]:
df.describe() #statistical summary

       vhigh vhigh.1     2   2.1 small   low  unacc
count   1727    1727  1727  1727  1727  1727   1727
unique     4       4     4     3     3     3      4
top     high    high     3     4   med   med  unacc
freq     432     432   432   576   576   576   1209

In [18]:
df [["buyingPrice","priceofMaintenance"]].describe() # statistical s

KeyError: "None of [Index(['buyingPrice', 'priceofMaintenance'], dtype='str')] are in the [columns]"