### **Business Understanding**
**About Data:** Development Relevance: The digital and information revolution has changed the way the world learns, communicates, does business, and treats illnesses. New information and communications technologies (ICT) offer vast opportunities for progress in all walks of life in all countries - opportunities for economic growth, improved health, better service delivery, learning through distance education, and social and cultural advances.

Today's smartphones and tablets have computer power equivalent to that of yesterday's computers and provide a similar range of functions. Device convergence is thus rendering the conventional definition obsolete.

Comparable statistics on access, use, quality, and affordability of ICT are needed to formulate growth-enabling policies for the sector and to monitor and evaluate the sector's impact on development. Although basic access data are available for many countries, in most developing countries little is known about who uses ICT; what they are used for (school, work, business, research, government); and how they affect people and businesses. The global Partnership on Measuring ICT for Development is helping to set standards, harmonize information and communications technology statistics, and build statistical capacity in developing countries. However, despite significant improvements in the developing world, the gap between the ICT haves and have-nots remains.
Statistical Concept: The number of in-scope individuals using the Internet is calculated by aggregating the weighted responses. The proportion of individuals using the Internet is expressed as a percentage and is calculated by dividing the total number of in-scope individuals using the Internet by the total number of in-scope individuals, and then multiplying the result by 100.

Note: Weighted average Operators have traditionally been the main source of telecommunications data, so information on subscriptions has been widely available for most countries. This gives a general idea of access, but a more precise measure is the penetration rate - the share of households with access to telecommunications.

Data source Aggregation Method: Weighted average

#### **Load Libraries**

In [7]:
import pandas as pd
 
#  enables us to view all the information sans ellipsisi/ minimization
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

#### **load Data**

In [8]:
df=pd.read_csv("data\WB_WDI_IT_NET_USER_ZS (1).csv", sep=";")

<>:1: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
<>:1: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
C:\Users\user\AppData\Local\Temp\ipykernel_4728\1881927459.py:1: SyntaxWarning: "\W" is an invalid escape sequence. Such sequences will not work in the future. Did you mean "\\W"? A raw string is also an option.
  df=pd.read_csv("data\WB_WDI_IT_NET_USER_ZS (1).csv", sep=";")

### **Data Understnding**
#### **High level view of the data**

In [9]:
df. head(10)

  STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,COMP_BREAKDOWN_1,COMP_BREAKDOWN_2,COMP_BREAKDOWN_3,TIME_PERIOD,OBS_VALUE,AGG_METHOD,UNIT_TYPE,DECIMALS,DATABASE_ID,TIME_FORMAT,UNIT_MULT,OBS_STATUS,OBS_CONF,FREQ_LABEL,REF_AREA_LABEL,INDICATOR_LABEL,SEX_LABEL,AGE_LABEL,URBANISATION_LABEL,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
0  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,Z...
1  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,Z...
2  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,A...
3  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,A...
4  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,E...
5  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,E...
6  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,T...
7  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,Y...
8  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,Z...
9  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,Z...

In [10]:
df.tail(10)

     STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,COMP_BREAKDOWN_1,COMP_BREAKDOWN_2,COMP_BREAKDOWN_3,TIME_PERIOD,OBS_VALUE,AGG_METHOD,UNIT_TYPE,DECIMALS,DATABASE_ID,TIME_FORMAT,UNIT_MULT,OBS_STATUS,OBS_CONF,FREQ_LABEL,REF_AREA_LABEL,INDICATOR_LABEL,SEX_LABEL,AGE_LABEL,URBANISATION_LABEL,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL
6886  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,A...
6887  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,A...
6888  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,N...
6889  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,S...
6890  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,S...
6891  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,T...
6892  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,S...
6893  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,S...
6894  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,T...
6895  datastructure,WB.DATA360:DS_DATA360(1.3),I,A,U...

In [11]:
rows, columns = df.shape
output = f"{rows} records and {columns} features"
print(output)

6896 records and 1 features

#### **Extract Columns**
Reason: The number of columns sem to be quite many, could we narrow down to the relevant columns?

In [12]:
features = df.columns # attaining a list of all the columns/ features
features

Index(['STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,COMP_BREAKDOWN_1,COMP_BREAKDOWN_2,COMP_BREAKDOWN_3,TIME_PERIOD,OBS_VALUE,AGG_METHOD,UNIT_TYPE,DECIMALS,DATABASE_ID,TIME_FORMAT,UNIT_MULT,OBS_STATUS,OBS_CONF,FREQ_LABEL,REF_AREA_LABEL,INDICATOR_LABEL,SEX_LABEL,AGE_LABEL,URBANISATION_LABEL,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL'], dtype='str')


We are checking the number of unique elemets per feature/column:
Reason: We can drop columns that do not contain constant data(it is the same from the first record to the last record), however, kinldy note there exists algorithms/ techniques that enable feature selection (we shall cpaturethem in AI session)

In [13]:
relevant_cols =[]
cols_to_drop = []
for feature in features: 

    if df[feature].nunique() > 1:
        relevant_cols.append(feature)
    else:
        cols_to_drop.append(feature)

    # print(f"FEATURE:{feature} || STATS: {df[feature].nunique()}") # nunique() returns the number of unique items within the columns
    # print("===============================")

In [14]:

len(relevant_cols)

1

In [16]:
relevant_cols

['STRUCTURE,STRUCTURE_ID,ACTION,FREQ,REF_AREA,INDICATOR,SEX,AGE,URBANISATION,UNIT_MEASURE,COMP_BREAKDOWN_1,COMP_BREAKDOWN_2,COMP_BREAKDOWN_3,TIME_PERIOD,OBS_VALUE,AGG_METHOD,UNIT_TYPE,DECIMALS,DATABASE_ID,TIME_FORMAT,UNIT_MULT,OBS_STATUS,OBS_CONF,FREQ_LABEL,REF_AREA_LABEL,INDICATOR_LABEL,SEX_LABEL,AGE_LABEL,URBANISATION_LABEL,UNIT_MEASURE_LABEL,COMP_BREAKDOWN_1_LABEL,COMP_BREAKDOWN_2_LABEL,COMP_BREAKDOWN_3_LABEL,AGG_METHOD_LABEL,UNIT_TYPE_LABEL,DECIMALS_LABEL,DATABASE_ID_LABEL,TIME_FORMAT_LABEL,UNIT_MULT_LABEL,OBS_STATUS_LABEL,OBS_CONF_LABEL']

In [17]:
len(cols_to_drop)

0

Select columns that contained only single values/ 1 unique value and use it to drop their respective columns to cretae a new dataframe

In [18]:
columns_to_drop = ["OBS_STATUS_LABEL", "OBS_CONF_LABEL","UNIT_MULT_LABEL","TIME_FORMAT_LABEL","DATABASE_ID_LABEL","DECIMALS_LABEL","UNIT_TYPE_LABEL","COMP_BREAKDOWN_3_LABEL","COMP_BREAKDOWN_2_LABEL","COMP_BREAKDOWN_1_LABEL",
"UNIT_MEASURE_LABEL","AGE_LABEL","SEX_LABEL","INDICATOR_LABEL","STRUCTURE", "STRUCTURE_ID","ACTION","FREQ","INDICATOR", "OBS_CONF_LABEL"]

In [19]:

len(columns_to_drop)

20

In [24]:
clean_df = df.drop(columns_to_drop , axis=1) # drop columns,  to make sure we drop purely the olumns we set axis to 1

KeyError: "['OBS_STATUS_LABEL', 'OBS_CONF_LABEL', 'UNIT_MULT_LABEL', 'TIME_FORMAT_LABEL', 'DATABASE_ID_LABEL', 'DECIMALS_LABEL', 'UNIT_TYPE_LABEL', 'COMP_BREAKDOWN_3_LABEL', 'COMP_BREAKDOWN_2_LABEL', 'COMP_BREAKDOWN_1_LABEL', 'UNIT_MEASURE_LABEL', 'AGE_LABEL', 'SEX_LABEL', 'INDICATOR_LABEL', 'STRUCTURE', 'STRUCTURE_ID', 'ACTION', 'FREQ', 'INDICATOR', 'OBS_CONF_LABEL'] not found in axis"

In [23]:
clean_df.shape

NameError: name 'clean_df' is not defined


Selecting relevant features and creating a new data fram

In [25]:
relevant_features = ["TIME_PERIOD", "OBS_VALUE","REF_AREA_LABEL"]

In [26]:
clean_df = df[relevant_features] # filtered our tagret columns

KeyError: "None of [Index(['TIME_PERIOD', 'OBS_VALUE', 'REF_AREA_LABEL'], dtype='str')] are in the [columns]"

In [27]:
rows, columns  = clean_df.shape
output = f"{rows} records and {columns} features"
print(output)

NameError: name 'clean_df' is not defined

In [28]:
clean_df.head()

NameError: name 'clean_df' is not defined